name: "Chromatic"

on:
  push:
    branches:
      - "main"
  pull_request:

permissions:
  contents: read
  statuses: write

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2

      - run: bun install

      - uses: chromaui/action@cad40970f69e7a6a5bef4ddfe42c01309ba17cb1 # latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          autoAcceptChanges: ${{ github.ref_name == 'main' && 'main' || '' }}
          exitOnceUploaded: true
